// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRKwW2SWhgoj8PeqjXv58TgvrVZJQhDsM',
    appId: '1:350746087662:web:c09caf4f8e433a634de3ff',
    messagingSenderId: '350746087662',
    projectId: 'simple-post-app-47463',
    authDomain: 'simple-post-app-47463.firebaseapp.com',
    storageBucket: 'simple-post-app-47463.firebasestorage.app',
    measurementId: 'G-Z0MXLWV5JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa989e-xeLQO29aHVBkJoOZ9O2FBUGZhw',
    appId: '1:350746087662:android:2a7e54afce96d1934de3ff',
    messagingSenderId: '350746087662',
    projectId: 'simple-post-app-47463',
    storageBucket: 'simple-post-app-47463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZVN-PwwxUcEWiMBMohhUZxx07EYPh7bY',
    appId: '1:350746087662:ios:130cacdc53e4da0c4de3ff',
    messagingSenderId: '350746087662',
    projectId: 'simple-post-app-47463',
    storageBucket: 'simple-post-app-47463.firebasestorage.app',
    iosBundleId: 'com.example.simplePostApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZVN-PwwxUcEWiMBMohhUZxx07EYPh7bY',
    appId: '1:350746087662:ios:130cacdc53e4da0c4de3ff',
    messagingSenderId: '350746087662',
    projectId: 'simple-post-app-47463',
    storageBucket: 'simple-post-app-47463.firebasestorage.app',
    iosBundleId: 'com.example.simplePostApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRKwW2SWhgoj8PeqjXv58TgvrVZJQhDsM',
    appId: '1:350746087662:web:060994dcf20528214de3ff',
    messagingSenderId: '350746087662',
    projectId: 'simple-post-app-47463',
    authDomain: 'simple-post-app-47463.firebaseapp.com',
    storageBucket: 'simple-post-app-47463.firebasestorage.app',
    measurementId: 'G-P4W53EVJ8H',
  );
}
